runs=(100,50,67,32,89)
total_runs=sum(runs)
highest_score=max(runs)
lowest_run=min(runs)
avg_run=total_runs/len(runs)
print("total runs:",total_runs)
print("highest score:",highest_score)
print("lowest run:",lowest_run)
print("avg run:",avg_run)