prices=(90,100,250,360,400)
total_bill=sum(prices)
print("total bill:",total_bill)
avg=total_bill/(len(prices))
print("average prices:",avg)
lowest_price=min(prices)
print("lowest price:",lowest_price)
highest_price=max(prices)
print("highest prices:",highest_price)